# Generated by Django 4.2.3 on 2023-07-24 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='username',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
